version: '3.7'

volumes:
  mariadb_data:
  grafana_data:

services:

  mariadb:
    image: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: >
      sh -c "
      echo 'CREATE USER IF NOT EXISTS \"${MYSQL_USER}\"@\"%\" IDENTIFIED BY \"${MYSQL_PASSWORD}\";' > /docker-entrypoint-initdb.d/init-db.sql &&
      echo 'GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR, SELECT ON *.* TO \"${MYSQL_USER}\"@\"%\";' >> /docker-entrypoint-initdb.d/init-db.sql &&
      echo 'FLUSH PRIVILEGES;' >> /docker-entrypoint-initdb.d/init-db.sql &&
      docker-entrypoint.sh mariadbd
      "

  node-exporter:
    image: bitnami/node-exporter
    ports:
      - "9100:9100"

  mysqld-exporter:
    image: bitnami/mysqld-exporter
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--config.my-cnf=/etc/mysql/my.cnf"
    environment:
      DATA_SOURCE_NAME: ${MYSQL_USER}:${MYSQL_PASSWORD}@(mariadb:3306)/${MYSQL_DATABASE}
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "9104:9104"

  prometheus:
    build: ./prometheus/
    depends_on:
      - node-exporter
      - mysqld-exporter
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    ports:
      - "3000:3000"