global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']