{
 "title": "Mysql dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество соединений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Запись данных InnoDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_writes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество тредов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество отправленных данных MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    { "expr": "mysql_global_status_bytes_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Чтение данных InnoDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_reads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество полученных данных MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_status_bytes_received",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}