{
 "title": "OS General",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Отправленный трафик",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество свободного места",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 0 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Полученный трафик",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество файловых дескрипторов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 9 },
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "__auto" }
   ]
  }
 ]
}